In [1]:
# importing libabries
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
# loading  raw datasets
few_db =  pd.read_excel("data/raw/FEWS_NET_Staple_Food_Price_Data.xlsx")
wfp_db = pd.read_csv("data/raw/wfp_food_prices_nga.csv")

In [3]:
few_db.head() # loading the top data from fews datasets

,country,market,admin_1,longitude,latitude,cpcv2,product,source_document,period_date,price_type,product_source,unit,unit_type,currency,value
0,Nigeria,Aba,Abia,7.37063,5.10719,P23490AA,Bread,Famine Early Warning Systems Network (FEWS NET...,2008-07-14,Retail,Local,ea,Item,NGN,NaN
1,Nigeria,Aba,Abia,7.37063,5.10719,P23490AA,Bread,Famine Early Warning Systems Network (FEWS NET...,2008-08-15,Retail,Local,ea,Item,NGN,NaN
2,Nigeria,Aba,Abia,7.37063,5.10719,P23490AA,Bread,Famine Early Warning Systems Network (FEWS NET...,2008-09-15,Retail,Local,ea,Item,NGN,NaN
3,Nigeria,Aba,Abia,7.37063,5.10719,P23490AA,Bread,Famine Early Warning Systems Network (FEWS NET...,2008-12-16,Retail,Local,ea,Item,NGN,NaN
4,Nigeria,Aba,Abia,7.37063,5.10719,P23490AA,Bread,Famine Early Warning Systems Network (FEWS NET...,2009-01-23,Retail,Local,ea,Item,NGN,NaN

In [4]:
wfp_db.head() # loading the top data in the wfp datasets

,date,admin1,admin2,market,market_id,latitude,longitude,category,commodity,commodity_id,unit,priceflag,pricetype,currency,price,usdprice
0,1/15/2002,Katsina,Jibia,Jibia (CBM),1038,13.08,7.24,cereals and tubers,Maize,51,KG,actual,Wholesale,NGN,175.92,1.54
1,1/15/2002,Katsina,Jibia,Jibia (CBM),1038,13.08,7.24,cereals and tubers,Millet,73,KG,actual,Wholesale,NGN,150.18,1.31
2,1/15/2002,Katsina,Jibia,Jibia (CBM),1038,13.08,7.24,cereals and tubers,Rice (imported),64,KG,actual,Wholesale,NGN,358.70,3.14
3,1/15/2002,Katsina,Jibia,Jibia (CBM),1038,13.08,7.24,cereals and tubers,Sorghum,65,KG,actual,Wholesale,NGN,155.61,1.36
4,1/15/2002,Katsina,Jibia,Jibia (CBM),1038,13.08,7.24,pulses and nuts,Beans (niebe),120,KG,actual,Wholesale,NGN,196.87,1.72

In [5]:
# getting the data shap
print("FEWS NET shape:", few_db.shape)
print("WFP shape:", wfp_db.shape)

FEWS NET shape: (315712, 15)
WFP shape: (87646, 16)

In [6]:
# getting the column list
print("FEWS NET columns:", few_db.columns.tolist())
print()
print("WFP columns:", wfp_db.columns.tolist())

FEWS NET columns: ['country', 'market', 'admin_1', 'longitude', 'latitude', 'cpcv2', 'product', 'source_document', 'period_date', 'price_type', 'product_source', 'unit', 'unit_type', 'currency', 'value']

WFP columns: ['date', 'admin1', 'admin2', 'market', 'market_id', 'latitude', 'longitude', 'category', 'commodity', 'commodity_id', 'unit', 'priceflag', 'pricetype', 'currency', 'price', 'usdprice']

In [7]:
# getting the datatypes of each columns
print("FEWS NET dtypes:")
print(few_db.dtypes)
print()
print("WFP dtypes:")
print(wfp_db.dtypes)

FEWS NET dtypes:
country             object
market              object
admin_1             object
longitude          float64
latitude           float64
cpcv2               object
product             object
source_document     object
period_date         object
price_type          object
product_source      object
unit                object
unit_type           object
currency            object
value              float64
dtype: object

WFP dtypes:
date             object
admin1           object
admin2           object
market           object
market_id         int64
latitude        float64
longitude       float64
category         object
commodity        object
commodity_id      int64
unit             object
priceflag        object
pricetype        object
currency         object
price           float64
usdprice        float64
dtype: object

In [8]:
# null checking
print("FEWS NET nulls:")
print(few_db.isnull().sum())
print() # notice that value in fews has 56719 missing 
print("WFP nulls:")
print(wfp_db.isnull().sum())

FEWS NET nulls:
country                0
market                 0
admin_1                0
longitude              0
latitude               0
cpcv2                  0
product                0
source_document        0
period_date            0
price_type             0
product_source         0
unit                   0
unit_type              0
currency               0
value              56719
dtype: int64

WFP nulls:
date            0
admin1          0
admin2          0
market          0
market_id       0
latitude        0
longitude       0
category        0
commodity       0
commodity_id    0
unit            0
priceflag       0
pricetype       0
currency        0
price           0
usdprice        0
dtype: int64

In [9]:
print("unique values in few_price_type :")
few_db['price_type'].unique()   # getting the unquie values unique values in price_type and pricetype . Notice both are standardize
print("unique values in wfp_pricetype :")
wfp_db['pricetype'].unique()

unique values in few_price_type :
unique values in wfp_pricetype :

array(['Wholesale', 'Retail'], dtype=object)

In [10]:
few_db["currency"].unique()
# checking for the unique value in currency but it only contain one value which is the NGN

array(['NGN'], dtype=object)

In [11]:
wfp_db["currency"].unique() # wfp(currency) has the same standard in few_db and has only one value

array(['NGN'], dtype=object)

In [12]:
few_db["unit"].unique()
# getting the unique values in unit column in fews notice: kg and tubers are in lowercase, L is uppercase, presence of '_'

array(['ea', 'kg', '100_kg', 'L', '30_L', '50_kg', '100_tubers',
       '60_tubers'], dtype=object)

In [13]:
wfp_db["unit"].unique()
# getting the unique values in unit column in wfp. both have the same column value , KG are in uppercase, same with L

array(['KG', '100 KG', '50 KG', 'Unit', '2.6 KG', '2.8 KG', '2.7 KG', 'L',
       '2.5 KG', '100 L', '2.1 KG', '400 G', '2.2 KG', '0.5 KG', '30 pcs',
       '1.3 KG', '300 G', '250 G', '500 G', '100 Tubers'], dtype=object)

In [14]:
few_db["product"].unique() # getting the unique values in product. some of the values have a bracket

array(['Bread', 'Cowpeas (Brown)', 'Cowpeas (White)', 'Diesel',
       'Gari (White)', 'Gari (Yellow)', 'Gasoline',
       'Groundnuts (Shelled)', 'Maize Grain (White)',
       'Maize Grain (Yellow)', 'Millet (Pearl)', 'Palm Oil (Refined)',
       'Rice (5% Broken)', 'Rice (Milled)', 'Sorghum (Brown)',
       'Sorghum (White)', 'Yams', 'Cattle (Male)', 'Goats (Male)',
       'Sheep (Male)'], dtype=object)

In [15]:
wfp_db["commodity"].unique() # same thing with commodity in wfb. column name are not the same thing

array(['Maize', 'Millet', 'Rice (imported)', 'Sorghum', 'Beans (niebe)',
       'Wheat', 'Maize (white)', 'Sorghum (white)',
       'Rice (milled, local)', 'Bread', 'Cassava meal (gari, yellow)',
       'Gari (white)', 'Maize (yellow)', 'Rice (local)',
       'Sorghum (brown)', 'Yam (Abuja)', 'Fuel (diesel)',
       'Fuel (petrol-gasoline)', 'Oil (palm)', 'Cowpeas (brown)',
       'Cowpeas (white)', 'Yam', 'Groundnuts (shelled)', 'Maize flour',
       'Meat (beef)', 'Meat (goat)', 'Milk (powder)', 'Oil (vegetable)',
       'Beans (red)', 'Beans (white)', 'Groundnuts', 'Onions', 'Fish',
       'Eggs', 'Bananas', 'Oranges', 'Spinach', 'Watermelons', 'Cowpeas',
       'Tomatoes', 'Salt', 'Sugar', 'Seasoning (maggi cube)'],
      dtype=object)

In [26]:
print("the max date")
max(few_db['period_date'])
# the max date in the period_date in few_db

the max date

'2024-09-18'

In [27]:
# the min date in the period_date in few_db. has 21 years coverage
print("the min date")
min(few_db['period_date'])

the min date

'2003-10-29'

In [31]:
print("the max date")
max(wfp_db['date']) # the max date in the period_date in wfp_db

the max date

'9/15/2025'

In [30]:
print("the min date")
min(wfp_db['date'])  # the min date in the period_date in wfp_db . has 23 years coverage

the min date

'1/15/2002'

In [34]:
print("FEWS unique markets:", few_db['market'].unique())
print() # getting the unique values in market.note wfp has more coverage than fews
print("WFP unique markets:", wfp_db['market'].unique())

FEWS unique markets: ['Aba' 'Aba, Akwete' 'Aba, Udele' 'Biu' 'Damaturu' 'Dandume'
 'Geidam, Kasuwan Shanu' 'Giwa' 'Gombe' 'Gombe, Tiken Shanu' 'Gujungu'
 'Gujungu, Kara' 'Gwandu, Dodoru' 'Ibadan, Akinyele' 'Ibadan, Bodija'
 'Ilela, Kara Shanu' 'Kano, Dawanau' 'Kaura Namoda' 'Lagos, Kara'
 'Lagos, Mile 12' 'Maiadua' 'Maiduguri' 'Maiduguri, Kasuwan Shanu'
 'Maigatari, Kara' 'Mubi' 'Mubi, Tike' 'Port-Harcourt, Trans-Amadi'
 'Potiskum' 'Potiskum, Tike' 'Saminaka']

WFP unique markets: ['Jibia (CBM)' 'Illela (CBM)' 'Mai Adoua (CBM)' 'Damassack (CBM)'
 'Dawanau' 'Mai Gatari (CBM)' 'Ibadan' 'Maiduguri' 'Lagos' 'Giwa'
 'Kaura Namoda' 'Aba' 'Gombe' 'Gujungu' 'Saminaka' 'Dandume' 'Gwandu'
 'Mubi' 'Biu' 'Damaturu' 'Potiskum' 'Abba Gamaram' 'Baga Road'
 'Bullunkutu' 'Budum' 'Custom' 'Kusawam Shanu' 'Monday' 'Tashan Bama'
 'Bolori Stores' 'Damaturu (Sunday Market)' 'Geidam' 'Gujba (Buni Yadi)'
 'Jakusko' 'Bade (Gashua)' 'Nguru' 'Yunusari' 'Yusufari' 'Bursari'
 'Gulani (Tettaba)' 'Gamboru' 'Kashuwan Shanu' 'Bayantasha' 'Damagum'
 'Nangere' 'Madagali' 'Michika' 'Damboa' 'Monguno' 'Gwoza Central' 'Pulka'
 'Bama' 'Konduga' 'Dikwa Central' 'Mafa' 'Banki' 'Machina Central'
 'Shani Main Market' 'Rann' 'Magumeri Central' 'Ngala' 'Gajiram' 'Biriri'
 'Gombi' 'Mubi North' 'Ngalang' 'Ngelzarma' 'Jimeta Grain']

In [37]:
print("\nFEWS unique states:", few_db['admin_1'].unique())
print() 
print("WFP unique states:", wfp_db['admin1'].unique())

FEWS unique states: ['Abia' 'Borno' 'Yobe' 'Katsina' 'Kaduna' 'Gombe' 'Jigawa' 'Kebbi' 'Oyo'
 'Sokoto' 'Kano' 'Zamfara' 'Lagos' 'Adamawa' 'Rivers']

WFP unique states: ['Katsina' 'Sokoto' 'Borno' 'Kano' 'Jigawa' 'Oyo' 'Lagos' 'Kaduna'
 'Zamfara' 'Abia' 'Gombe' 'Kebbi' 'Adamawa' 'Yobe']